### ISSUE TITLE
Unhandle promise rejection

### ISSUE THREAD

**Issue by ian-s-mcb** [kkemple/gatsby-amplify-performant-apps#2]
Whenever I click the blog post like button, I get browser console error about an unhandled promise rejection. As it stands, I can't like anything with the app.

Could you let know what's going wrong with your app? I'd love to use it if I could get it to work.

### Screenshot of error
![screenshot-hacknoon_error_unhandled_promise_2019-04-26](https://user-images.githubusercontent.com/2540024/56836784-3e13df80-6846-11e9-9ce3-4ccfa7ab4205.png)

### Steps to reproduce the error:

```bash
gatsby new hnga-1 https://github.com/kkemple/gatsby-amplify-performant-apps
cd hnga-1/
rm -rf amplify/ src/graphql/
git add .
git commit -m "Remove amplify, graphql directory"
git status
amplify configure
amplify init
amplify add auth
amplify add api
vim amplify/backend/api/hnga/schema.graphql
# Replace contents with:
# type PostLike @model @auth(rules: [{ allow: owner, ownerField: "userId" }]) {
#    id: ID!
#    userId: String!
#    postId: String!
# }
amplify push
yarn develop
```

**Comment by ian-s-mcb** [comment]
If you want to look at the repo I used to produce this error, you can find it here:

https://gitlab.com/ian-s-mcb/hnga-1

**Comment by fullspectrumprocessing** [comment]
@ian-s-mcb  Hey was there ever any solution to this issue?? I had a similar problem last night and couldn't figure it out. The mutations and queries all work in the GraphQL Playground but I keep getting that error on the Front end. I found something on stackoverflow about putting the function ina try & catch ?? Lmk if you found anything please

**Comment by ian-s-mcb** [comment]
No solution. Plus, this starter is orphaned. @kkemple isn't maintaining it or responding to comments/emails about it.

What worked for me was to use [the other Gatsby Amplify](https://www.gatsbyjs.org/starters/dabit3/gatsby-auth-starter-aws-amplify/), however that starter has flaws, so I fixed them in [this starter](https://gitlab.com/ian-s-mcb/gatsby-basic-amplify-auth). I'm available if you have any questions.

**Comment by fullspectrumprocessing** [comment]
Okay thanks ill def be asking some question! Thanks for replying so soon. I was getting frustrated with his starter smh things just aren't adding up. I'll check out the starters you just shared.

**Comment by ian-s-mcb** [comment]
No sweat. Happy to offer help. Feel free to email me or post issues on [my starter](https://gitlab.com/ian-s-mcb/gatsby-basic-amplify-auth).

**Comment by kkemple** [comment]
Hey! I didn't see this until now so I do apologize for that. This isn't an official Gatsby starter either, was meant as an example application. However, the reason you are receiving that error is because in your schema you define the userId as required so the generated createPostLike input wants it to be present. If you compare the schema here in this directory (https://github.com/kkemple/gatsby-amplify-performant-apps/blob/master/amplify/backend/api/amplifygatsbyexample/schema.graphql#L3) its not marked as required for this reason.
